/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BenefitsRouteImport } from './routes/benefits'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as MembershipIndexRouteImport } from './routes/membership.index'
import { Route as MembershipApplyRouteImport } from './routes/membership.apply'
import { Route as MembershipStatusRouteImport } from './routes/membership.status'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsRoute = BenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipIndexRoute = MembershipIndexRouteImport.update({
  id: '/membership/',
  path: '/membership/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipApplyRoute = MembershipApplyRouteImport.update({
  id: '/membership/apply',
  path: '/membership/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipStatusRoute = MembershipStatusRouteImport.update({
  id: '/membership/status',
  path: '/membership/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benefits': typeof BenefitsRoute
  '/contact': typeof ContactRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/admin/$': typeof AdminSplatRoute
  '/events/$slug': typeof EventsSlugRoute
  '/membership/apply': typeof MembershipApplyRoute
  '/membership/status': typeof MembershipStatusRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/membership/': typeof MembershipIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benefits': typeof BenefitsRoute
  '/contact': typeof ContactRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/admin/$': typeof AdminSplatRoute
  '/events/$slug': typeof EventsSlugRoute
  '/membership/apply': typeof MembershipApplyRoute
  '/membership/status': typeof MembershipStatusRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/membership': typeof MembershipIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benefits': typeof BenefitsRoute
  '/contact': typeof ContactRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/admin/$': typeof AdminSplatRoute
  '/events/$slug': typeof EventsSlugRoute
  '/membership/apply': typeof MembershipApplyRoute
  '/membership/status': typeof MembershipStatusRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/membership/': typeof MembershipIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/benefits'
    | '/contact'
    | '/get-started'
    | '/login'
    | '/admin/$'
    | '/events/$slug'
    | '/membership/apply'
    | '/membership/status'
    | '/products/$slug'
    | '/admin/'
    | '/events/'
    | '/membership/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/benefits'
    | '/contact'
    | '/get-started'
    | '/login'
    | '/admin/$'
    | '/events/$slug'
    | '/membership/apply'
    | '/membership/status'
    | '/products/$slug'
    | '/admin'
    | '/events'
    | '/membership'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/benefits'
    | '/contact'
    | '/get-started'
    | '/login'
    | '/admin/$'
    | '/events/$slug'
    | '/membership/apply'
    | '/membership/status'
    | '/products/$slug'
    | '/admin/'
    | '/events/'
    | '/membership/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BenefitsRoute: typeof BenefitsRoute
  ContactRoute: typeof ContactRoute
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  AdminSplatRoute: typeof AdminSplatRoute
  EventsSlugRoute: typeof EventsSlugRoute
  MembershipApplyRoute: typeof MembershipApplyRoute
  MembershipStatusRoute: typeof MembershipStatusRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  MembershipIndexRoute: typeof MembershipIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits': {
      id: '/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof BenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/': {
      id: '/membership/'
      path: '/membership'
      fullPath: '/membership/'
      preLoaderRoute: typeof MembershipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/apply': {
      id: '/membership/apply'
      path: '/membership/apply'
      fullPath: '/membership/apply'
      preLoaderRoute: typeof MembershipApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/status': {
      id: '/membership/status'
      path: '/membership/status'
      fullPath: '/membership/status'
      preLoaderRoute: typeof MembershipStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BenefitsRoute: BenefitsRoute,
  ContactRoute: ContactRoute,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  AdminSplatRoute: AdminSplatRoute,
  EventsSlugRoute: EventsSlugRoute,
  MembershipApplyRoute: MembershipApplyRoute,
  MembershipStatusRoute: MembershipStatusRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  MembershipIndexRoute: MembershipIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
